# Generated by Django 3.2.13 on 2022-07-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('employment_status', models.IntegerField(choices=[(1, 'Employed'), (2, 'Unemployed'), (3, 'Self-employed')], default=1)),
                ('ui_feedback', models.TextField()),
            ],
        ),
    ]
