# Generated by Django 3.2.13 on 2022-07-01 21:19

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentuser',
            name='id',
        ),
        migrations.AddField(
            model_name='experimentuser',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False),
        ),
    ]
