# Generated by Django 3.2.13 on 2022-07-03 16:50

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackui', '0003_auto_20220703_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentuser',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
