# Generated by Django 3.2.13 on 2022-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackui', '0004_alter_experimentuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentuser',
            name='uid',
            field=models.AutoField(default=1000000000, primary_key=True, serialize=False),
        ),
    ]
