# Generated by Django 3.2.13 on 2022-07-03 19:10

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackui', '0005_alter_experimentuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentuser',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
