# Generated by Django 3.2.13 on 2022-07-03 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackui', '0006_alter_experimentuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentuser',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
